module.exports = {
    serverStatusHandler: require('./helpers/serverStatusHandler'),

    registerUserHandler: require('./users/registerUserHandler'),
    searchUserHandler: require('./users/searchUserHandler'),
    validateUserHandler: require('./users/validateUserHandler'),
    forgotPasswordHandler: require('./users/forgotPasswordHandler'),
    recoverPasswordHandler: require('./users/recoverPasswordHandler'),
    // updatePasswordHandler: require('./users/updatePasswordHandler'),
    setNewPasswordHandler: require('./users/setNewPasswordHandler'),
    updateUserPasswordHandler: require('./users/updateUserPasswordHandler'),
    retrieveUserHandler: require('./users/retrieveUserHandler'),
    authenticateUserHandler: require('./users/authenticateUserHandler'),
    updateUserNameHandler: require('./users/updateUserNameHandler'),
    confirmNewUserEmailHandler: require('./users/confirmNewUserEmailHandler'),
    updateUserEmailHandler: require('./users/updateUserEmailHandler'),
    updateUserImageHandler: require('./users/updateUserImageHandler'),

    checkLoggedInUserHandler: require('./users/checkLoggedInUserHandler'),

    checkIfHasPlaygroundsNearHandler: require('./playgrounds/checkIfHasPlaygroundsNearHandler'),
    addPlaygroundHandler: require('./playgrounds/addPlaygroundHandler'),
    editPlaygroundElementsHandler: require('./playgrounds/editPlayground/editPlaygroundElementsHandler'),
    editPlaygroundSunExpositionHandler: require('./playgrounds/editPlayground/editPlaygroundSunExpositionHandler'),
    editPlaygroundDescriptionHandler: require('./playgrounds/editPlayground/editPlaygroundDescriptionHandler'),
    editPlaygroundAddImagesHandler: require('./playgrounds/editPlayground/editPlaygroundAddImagesHandler'),
    deletePlaygroundostHandler: require('./playgrounds/deletePostHandler'),
    retrievePlaygroundsHandler: require('./playgrounds/retrievePlaygroundsHandler'),
    retrieveFromFilterHandler: require('./playgrounds/searchPlaygrounds/retrieveFromFilterHandler'),
    retrieveCitiesFromDatabaseHandler: require('./playgrounds/searchPlaygrounds/retrieveCitiesFromDatabaseHandler'),
    searchAutocompleteCitiesHandler: require('./playgrounds/searchPlaygrounds/searchAutocompleteCitiesHandler'),
    retrievePlaygroundsFromCityHandler: require('./playgrounds/searchPlaygrounds/retrievePlaygroundsFromCityHandler'),
    retrieveCityFromSearchHandler: require('./playgrounds/searchPlaygrounds/retrieveCityFromSearchHandler'),
    retrieveLikedPlaygroundsHandler: require('./playgrounds/retrieveLikedPlaygroundsHandler'),
    retrieveSavedPostsHandler: require('./playgrounds/retrieveSavedPostsHandler'),
    retrievePlaygroundByIdHandler: require('./playgrounds/retrievePlaygroundByIdHandler'),
    toggleLikePlaygroundHandler: require('./playgrounds/toggleLikePlaygroundHandler'),
    toggleSavePostHandler: require('./playgrounds/toggleSavePostHandler')
}