module.exports = {
    retrievePlaygrounds: require('./retrievePlaygrounds'),
    searchAutocompleteCities: require('./searchPlaygrounds/searchAutocompleteCities'),
    retrieveDataFromCurrentLocation: require('./searchPlaygrounds/retrieveDataFromCurrentLocation'),
    retrievePlaygroundsFromCity: require('./searchPlaygrounds/retrievePlaygroundsFromCity'),
    retrieveCoordinatesFromCity: require('./searchPlaygrounds/retrieveCoordinatesFromCity'),
    retrieveFromFilter: require('./searchPlaygrounds/retrieveFromFilter'),
    retrieveCitiesFromDatabase: require('./searchPlaygrounds/retrieveCitiesFromDatabase'),
    retrieveCityFromSearch: require('./searchPlaygrounds/retrieveCityFromSearch'),
    checkIfHasPlaygroundsNear: require('./checkIfHasPlaygroundsNear'),
    addPlayground: require('./addPlayground'),
    editPlaygroundElements: require('./editPlayground/editPlaygroundElements'),
    editPlaygroundSunExposition: require('./editPlayground/editPlaygroundSunExposition'),
    editPlaygroundDescription: require('./editPlayground/editPlaygroundDescription'),
    editPlaygroundAddImages: require('./editPlayground/editPlaygroundAddImages'),
    retrieveLikedPlaygrounds: require('./retrieveLikedPlaygrounds'),
    retrievePlaygroundById: require('./retrievePlaygroundById'),
    toggleLikePlayground: require('./toggleLikePlayground'),
}